#!/bin/sh
#
# APF6 Wi-Fi
#

start_chip() {
	if [ ! -d /sys/class/gpio/gpio40 ]; then
		echo 40 > /sys/class/gpio/export
	fi

	echo out > /sys/class/gpio/gpio40/direction

	sleep 1
	echo 1 > /sys/class/gpio/gpio40/value
	sleep 1
	echo 0 > /sys/class/gpio/gpio40/value
	sleep 1
	echo 1 > /sys/class/gpio/gpio40/value
	sleep 1
}

stop_chip() {
	if [ ! -d /sys/class/gpio/gpio40 ]; then
		echo 40 > /sys/class/gpio/export
	fi

	echo out > /sys/class/gpio/gpio40/direction
	sleep 1
}

start() {
	ifconfig wlan0 down > /dev/null 2>&1

	start_chip

	modprobe -q wlcore_sdio
	modprobe -q wl12xx

	sleep 1

	ifconfig wlan0 up
}

stop() {
	ifconfig wlan0 down > /dev/null 2>&1

	stop_chip
}

restart() {
	stop
	start
}

calibrate() {
	if [ ! -z "$1" ]; then
		echo "Calibrating"
		
		stop

		calibrator set ref_nvs /usr/share/ti-utils/ini_files/127x/TQS_S_2.6.ini
		mv new-nvs.bin /lib/firmware/ti-connectivity/wl1271-nvs.bin
		calibrator set nvs_mac /lib/firmware/ti-connectivity/wl1271-nvs.bin $1

		start_chip

		modprobe -q wlcore_sdio
		modprobe -q wl12xx

		sleep 2

		calibrator plt calibrate dual

		stop_chip
	else
		echo "Error: MAC address not given."
	fi
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  calibrate)
  	calibrate "$2"
  	;;
  *)
	echo $"Usage: $0 {start|stop|restart|calibrate <MAC address>}"
	exit 1
esac

exit $?

